spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
  servlet:
    multipart:
      enabled: true
      location: ${IMAGE_STORAGE_LOCATION}
      maxFileSize: 10MB
      maxRequestSize: 10MB
    web:
      resources:
        static-locations: classpath:/

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/open-api-3.0.1.json
    path: /docs/swagger

