name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  CODEDEPLOY_APP_NAME: ${{ secrets.CODEDEPLOY_APP_NAME }}
  CODEDEPLOY_GROUP_NAME: ${{ secrets.CODEDEPLOY_GROUP_NAME }}
  ACCESS_EXPIRATION_MINUTES: ${{ secrets.ACCESS_EXPIRATION_MINUTES }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
  IMAGE_STORAGE_LOCATION: ${{ secrets.IMAGE_STORAGE_LOCATION }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  REFRESH_EXPIRATION_MINUTES: ${{ secrets.REFRESH_EXPIRATION_MINUTES }}

  REDIRECT_URL8000: ${{ secrets.REDIRECT_URL8000 }}
  API_KEY: ${{ secrets.API_KEY }}

  # s3
  AWS_ACCESS_KEY2: ${{ secrets.AWS_ACCESS_KEY2 }}
  AWS_SECRET_ACCESS_KEY2: ${{ secrets.AWS_SECRET_ACCESS_KEY2 }}

  FILE_LOCATION: ${{ secrets.FILE_LOCATION }}
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [6]

    steps:
    - name: Start Redis v${{ matrix.redis-version }}
      uses: superchargejs/redis-github-action@1.1.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Add permission
      run: chmod +x server/gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        build-root-directory: server
    
    - name: Make zip file
      run: zip -r ./build.zip .
      shell: bash
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./build.zip s3://$S3_BUCKET_NAME/build.zip
      
    - name: Code Deploy
      run: >
        aws deploy create-deployment --application-name $CODEDEPLOY_APP_NAME
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name $CODEDEPLOY_GROUP_NAME
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=build.zip
